package com.lnoxx.myanimeview.ui.search

import com.lnoxx.myanimeview.R

enum class AnimeTvType (val query: String, val localizeTextResId: Int){
    NONE("", R.string.none),
    TV ("tv", R.string.tv),
    MOVIE ("movie", R.string.movie),
    OVA ("ova", R.string.ova),
    SPECIAL ("special", R.string.special),
}

enum class AnimeStatus(val query: String, val localizeTextResId: Int){
    NONE("", R.string.none),
    AIRING ("airing", R.string.airing),
    COMPLETE ("complete", R.string.complete),
    UPCOMING ("upcoming", R.string.upcoming),
}

enum class AnimeRating(val query: String, val localizeTextResId: Int){
    NONE("", com.lnoxx.myanimeview.R.string.none),
    G ("g", com.lnoxx.myanimeview.R.string.G),
    PG ("pg", com.lnoxx.myanimeview.R.string.PG),
    PG13 ("pg13", com.lnoxx.myanimeview.R.string.PG13),
    R17 ("r17", com.lnoxx.myanimeview.R.string.R17),
    R ("r", com.lnoxx.myanimeview.R.string.R),
    RX ("rx", com.lnoxx.myanimeview.R.string.RX),
}

enum class SortFilter(val query: String, val localizeTextResId: Int){
    TITLE ("title", R.string.title_sort),
    START_DATE ("start_date", R.string.date_sort),
    EPISODES ("episodes", R.string.episodes_sort),
    SCORE ("score", R.string.score_sort),
    RANK ("rank", R.string.rank_sort),
    POPULARITY ("popularity", R.string.popylarity_sort),
}

enum class SortType(val query: String, val localizeTextResId: Int){
    DESC ("desc", R.string.desc),
    ASC ("asc", R.string.asc),
}

data class SearchFilter(
    var query: String? = null,
    var type: AnimeTvType? = null,
    var minScore: Float = 0f,
    var maxFloat: Float = 10f,
    var status: AnimeStatus? = null,
    var rating: AnimeRating? = null,
    var sfw: Boolean = false,
    var sortFilter: SortFilter = SortFilter.POPULARITY,
    var sortType: SortType = SortType.ASC,
    val genres: MutableSet<Genre> = mutableSetOf(),
)

enum class Genre(val malId: Int, val text: String) {
    ACTION(1, "Action"),
    ADVENTURE(2, "Adventure"),
    AVANT_GARDE(5, "Avant Garde"),
    AWARD_WINNING(46, "Award Winning"),
    BOYS_LOVE(28, "Boys Love"),
    COMEDY(4, "Comedy"),
    DRAMA(8, "Drama"),
    FANTASY(10, "Fantasy"),
    GIRLS_LOVE(26, "Girls Love"),
    GOURMET(47, "Gourmet"),
    HORROR(14, "Horror"),
    MYSTERY(7, "Mystery"),
    ROMANCE(22, "Romance"),
    SCI_FI(24, "Sci-Fi"),
    SLICE_OF_LIFE(36, "Slice of Life"),
    SPORTS(30, "Sports"),
    SUPERNATURAL(37, "Supernatural"),
    SUSPENSE(41, "Suspense"),
    ECCHI(9, "Ecchi"),
    EROTICA(49, "Erotica"),
    HENTAI(12, "Hentai"),
    ADULT_CAST(50, "Adult Cast"),
    ANTHROPOMORPHIC(51, "Anthropomorphic"),
    CGDCT(52, "CGDCT"),
    CHILDCARE(53, "Childcare"),
    COMBAT_SPORTS(54, "Combat Sports"),
    CROSSDRESSING(81, "Crossdressing"),
    DELINQUENTS(55, "Delinquents"),
    DETECTIVE(39, "Detective"),
    EDUCATIONAL(56, "Educational"),
    GAG_HUMOR(57, "Gag Humor"),
    GORE(58, "Gore"),
    HAREM(35, "Harem"),
    HIGH_STAKES_GAME(59, "High Stakes Game"),
    HISTORICAL(13, "Historical"),
    IDOLS_FEMALE(60, "Idols (Female)"),
    IDOLS_MALE(61, "Idols (Male)"),
    ISEKAI(62, "Isekai"),
    IYASHIKEI(63, "Iyashikei"),
    LOVE_POLYGON(64, "Love Polygon"),
    MAGICAL_SEX_SHIFT(65, "Magical Sex Shift"),
    MAHOU_SHOUJO(66, "Mahou Shoujo"),
    MARTIAL_ARTS(17, "Martial Arts"),
    MECHA(18, "Mecha"),
    MEDICAL(67, "Medical"),
    MILITARY(38, "Military"),
    MUSIC(19, "Music"),
    MYTHOLOGY(6, "Mythology"),
    ORGANIZED_CRIME(68, "Organized Crime"),
    OTAKU_CULTURE(69, "Otaku Culture"),
    PARODY(20, "Parody"),
    PERFORMING_ARTS(70, "Performing Arts"),
    PETS(71, "Pets"),
    PSYCHOLOGICAL(40, "Psychological"),
    RACING(3, "Racing"),
    REINCARNATION(72, "Reincarnation"),
    REVERSE_HAREM(73, "Reverse Harem"),
    ROMANTIC_SUBTEXT(74, "Romantic Subtext"),
    SAMURAI(21, "Samurai"),
    SCHOOL(23, "School"),
    SHOWBIZ(75, "Showbiz"),
    SPACE(29, "Space"),
    STRATEGY_GAME(11, "Strategy Game"),
    SUPER_POWER(31, "Super Power"),
    SURVIVAL(76, "Survival"),
    TEAM_SPORTS(77, "Team Sports"),
    TIME_TRAVEL(78, "Time Travel"),
    VAMPIRE(32, "Vampire"),
    VIDEO_GAME(79, "Video Game"),
    VISUAL_ARTS(80, "Visual Arts"),
    WORKPLACE(48, "Workplace"),
    JOSEI(43, "Josei"),
    KIDS(15, "Kids"),
    SEINEN(42, "Seinen"),
    SHOUJO(25, "Shoujo"),
    SHOUNEN(27, "Shounen")
}
